services:
  nextcloud-db:
    container_name: nextcloud-db
    image: mysql
    restart: always
    volumes:
      - ./nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud-root
      - MYSQL_PASSWORD=nextcloud-pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    ports:
      - 8081:80
    volumes:
      - ./nextcloud:/var/www/html
    restart: always
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_PASSWORD=nextcloud-pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
