services:
  openproject:
    # 初回ユーザーパスワード admin/admin
    container_name: openproject
    image: openproject/openproject:15
    ports:
      - 8080:80
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=secret
      - OPENPROJECT_HOST__NAME=localhost:8080
      - OPENPROJECT_HTTPS=false
      - OPENPROJECT_DEFAULT__LANGUAGE=ja
